name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    # NOTE: Default option does not include `-o pipefail` as documented
    # unless explicitly specifying the `bash` shell.
    # https://github.com/actions/runner/issues/353
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 3

    steps:
      - name: Checkout branch
        uses: actions/checkout@v5.0.0

      - name: Set up Deno
        uses: denoland/setup-deno@v2.0.3
        with:
          deno-version: "2.4.3"

      - name: Check types
        run: |
          deno check '**/*.ts'

      - name: Check linting
        run: |
          deno lint '**/*.ts'

      - name: Check formatting
        run: |
          deno fmt --check '**/*.ts'

  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    needs:
      - lint

    steps:
      - name: Checkout branch
        uses: actions/checkout@v5.0.0

      - name: Set up Deno
        uses: denoland/setup-deno@v2.0.3
        with:
          deno-version: "2.4.3"

      - name: Test build task
        run: |
          deno task build
